apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
      - name: timestamp-generator
        image: sankethdhub08/log-gen:latest
        volumeMounts:
        - name: shared-data
          mountPath: /app/shared
      - name: log-reader
        image: sankethdhub08/hash-gen:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: shared-data
          mountPath: /app/shared
      volumes:
      - name: shared-data
        emptyDir: {}

