apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
      - name: log-output-app
        image: sankethdhub08/log-output-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

