FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package*.json ./

RUN pnpm install

COPY hash-startup.sh ./
COPY hash-reader.js ./

CMD ["sh", "-c", "./hash-startup.sh && pnpm start:reader"]

EXPOSE 3000