apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: ping-pong-app
spec:
  containers:
    - name: debug-container
      image: nicolaka/netshoot:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      stdin: true
      tty: true
