apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: quay.io/external_storage/nfs-subdir-external-provisioner:latest
        volumeMounts:
        - name: shared-data
          mountPath: /nfs/shared
        - name: nfs-provisioner-config
          mountPath: /etc/provisioner/config/provisioner.conf
          subPath: provisioner.conf
          readOnly: true
      volumes:
      - name: shared-data
        nfs:
          server: nfs-server-service.default.svc.cluster.local
          path: /nfs/shared
      - name: nfs-provisioner-config
        configMap:
          name: nfs-provisioner-configmap