apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: todo-app
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 84
      targetPort: 80
  type: ClusterIP