apiVersion: batch/v1
kind: CronJob
metadata:
  name: image-fetch-cronjob
spec:
  schedule: "*/2 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: image-fetch-cronjob
            image: busybox
            args:
            - /bin/sh
            - -c
            - |
                echo "$(date) - Writing to file..." > /app/shared/cronjob-output.txt
                echo "$(date) - File written successfully!"
            volumeMounts:
            - name: shared-data-pv
              mountPath: /app/shared
          restartPolicy: OnFailure
          volumes:
          - name: shared-data-pv
            persistentVolumeClaim:
              claimName: shared-pvc