apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteMany # Multiple pods can read/write to the volume
  persistentVolumeReclaimPolicy: Retain # Retain the volume even after the claim is deleted
  storageClassName: manual
  nfs:
    