apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
      - name: ping-pong-app
        image: sankethdhub08/ping-pong-app:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: pingpong-secret
              key: POSTGRES_URL
        volumeMounts:
        - name: shared-data-pv
          mountPath: /app/shared
      volumes:
      - name: shared-data-pv
        persistentVolumeClaim:
          claimName: shared-pvc

