apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: todo-app
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 86
      targetPort: 5000
  type: ClusterIP